--------------------------------------------------------
--  File created - Friday-June-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MATA_KULIAH
--------------------------------------------------------

  CREATE TABLE "HR"."MATA_KULIAH" 
   (	"KD_MK" VARCHAR2(10 BYTE), 
	"NAMA_MK" VARCHAR2(35 BYTE), 
	"JUMLAH_SKS" NUMBER, 
	"KODE_DOSEN" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.MATA_KULIAH
Insert into HR.MATA_KULIAH (KD_MK,NAMA_MK,JUMLAH_SKS,KODE_DOSEN) values ('M_TI_3','STRUKTUR DATA',2,'D_TI_1');
Insert into HR.MATA_KULIAH (KD_MK,NAMA_MK,JUMLAH_SKS,KODE_DOSEN) values ('M_TI_4','KEAMANAN BASISDATA',3,'D_TI_2');
Insert into HR.MATA_KULIAH (KD_MK,NAMA_MK,JUMLAH_SKS,KODE_DOSEN) values ('M_TI_1','SISTEM OPERASI',3,'D_TI_1');
Insert into HR.MATA_KULIAH (KD_MK,NAMA_MK,JUMLAH_SKS,KODE_DOSEN) values ('M_TI_2','PEMOGRAMAN WEB',2,'D_TI_2');
Insert into HR.MATA_KULIAH (KD_MK,NAMA_MK,JUMLAH_SKS,KODE_DOSEN) values ('M_TI_5','PEMOGRAMAN BASISDATA',2,'D_TI_2');
Insert into HR.MATA_KULIAH (KD_MK,NAMA_MK,JUMLAH_SKS,KODE_DOSEN) values ('M_FST_1','KALKULUS',3,'D_TI_1');
Insert into HR.MATA_KULIAH (KD_MK,NAMA_MK,JUMLAH_SKS,KODE_DOSEN) values ('M_USD_1','AGAMA',2,'D_TI_1');
Insert into HR.MATA_KULIAH (KD_MK,NAMA_MK,JUMLAH_SKS,KODE_DOSEN) values ('M_USD_2','TEOLOGI MORAL',2,'D_TI_2');
Insert into HR.MATA_KULIAH (KD_MK,NAMA_MK,JUMLAH_SKS,KODE_DOSEN) values ('M_USD_3','PANCASILA',2,'D_TI_1');
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TABLE1_PK" ON "HR"."MATA_KULIAH" ("KD_MK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MATA_KULIAH
--------------------------------------------------------

  ALTER TABLE "HR"."MATA_KULIAH" MODIFY ("KD_MK" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MATA_KULIAH" MODIFY ("NAMA_MK" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MATA_KULIAH" MODIFY ("JUMLAH_SKS" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MATA_KULIAH" MODIFY ("KODE_DOSEN" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MATA_KULIAH" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("KD_MK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATA_KULIAH
--------------------------------------------------------

  ALTER TABLE "HR"."MATA_KULIAH" ADD FOREIGN KEY ("KODE_DOSEN")
	  REFERENCES "HR"."DOSEN" ("KODE_DOSEN") ENABLE;
