--------------------------------------------------------
--  File created - Friday-June-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAHASISWA
--------------------------------------------------------

  CREATE TABLE "HR"."MAHASISWA" 
   (	"NIM" VARCHAR2(20 BYTE), 
	"NAMA" VARCHAR2(35 BYTE), 
	"ALAMAT" VARCHAR2(50 BYTE), 
	"TANGGAL_LAHIR" DATE, 
	"PASSWORD" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.MAHASISWA
Insert into HR.MAHASISWA (NIM,NAMA,ALAMAT,TANGGAL_LAHIR,PASSWORD) values ('145314101','JELISTINA','MEDAN',to_date('12-JUN-96','DD-MON-RR'),'12345');
Insert into HR.MAHASISWA (NIM,NAMA,ALAMAT,TANGGAL_LAHIR,PASSWORD) values ('145314009','ARIE','JAKARTA',to_date('19-JUL-96','DD-MON-RR'),'54321');
--------------------------------------------------------
--  DDL for Index MAHASISWA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MAHASISWA_PK" ON "HR"."MAHASISWA" ("NIM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MAHASISWA
--------------------------------------------------------

  ALTER TABLE "HR"."MAHASISWA" ADD CONSTRAINT "MAHASISWA_PK" PRIMARY KEY ("NIM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("NIM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("NAMA" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("ALAMAT" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("TANGGAL_LAHIR" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("PASSWORD" NOT NULL ENABLE);
