--------------------------------------------------------
--  File created - Friday-June-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DOSEN
--------------------------------------------------------

  CREATE TABLE "HR"."DOSEN" 
   (	"KODE_DOSEN" VARCHAR2(20 BYTE), 
	"NAMA_DOSEN" VARCHAR2(35 BYTE), 
	"NO_TELEPON" VARCHAR2(20 BYTE), 
	"ALAMAT" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.DOSEN
Insert into HR.DOSEN (KODE_DOSEN,NAMA_DOSEN,NO_TELEPON,ALAMAT) values ('D_TI_1','TATIK','082362591200','JOGJA');
Insert into HR.DOSEN (KODE_DOSEN,NAMA_DOSEN,NO_TELEPON,ALAMAT) values ('D_TI_2','WAWAN','085262177709','JOGJA');
--------------------------------------------------------
--  DDL for Index DOSEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."DOSEN_PK" ON "HR"."DOSEN" ("KODE_DOSEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DOSEN
--------------------------------------------------------

  ALTER TABLE "HR"."DOSEN" ADD CONSTRAINT "DOSEN_PK" PRIMARY KEY ("KODE_DOSEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."DOSEN" MODIFY ("KODE_DOSEN" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."DOSEN" MODIFY ("NAMA_DOSEN" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."DOSEN" MODIFY ("NO_TELEPON" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."DOSEN" MODIFY ("ALAMAT" NOT NULL ENABLE);
